// src/services/adminServices.js
import axios from 'axios';

const API_URL = '/api/admin';

// Get all users (students and recruiters)
const getUsers = async (token) => {
  try {
    const response = await axios.get(`${API_URL}/users`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    return response.data;
  } catch (error) {
    throw new Error(error.response ? error.response.data.message : 'Error fetching users');
  }
};

// Get reports generated by the system
const getReports = async (token) => {
  try {
    const response = await axios.get(`${API_URL}/reports`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    return response.data;
  } catch (error) {
    throw new Error(error.response ? error.response.data.message : 'Error fetching reports');
  }
};

// Delete a user (admin only)
const deleteUser = async (userId, token) => {
  try {
    const response = await axios.delete(`${API_URL}/users/${userId}`, {
      headers: { Authorization: `Bearer ${token}` }
    });
    return response.data;
  } catch (error) {
    throw new Error(error.response ? error.response.data.message : 'Error deleting user');
  }
};

// Generate a report (admin only)
const generateReport = async (reportData, token) => {
  try {
    const response = await axios.post(
      `${API_URL}/reports`,
      reportData,
      { headers: { Authorization: `Bearer ${token}` } }
    );
    return response.data;
  } catch (error) {
    throw new Error(error.response ? error.response.data.message : 'Error generating report');
  }
};

export { getUsers, getReports, deleteUser, generateReport };
